name: Tags

on:
  merge_group:
  pull_request_target:
    branches:
      - main
    types:
      - closed
  push:
    tags:
      - v*.*.*
  workflow_call:

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Reject workflow pull requests
        if: |
          github.event.pull_request.merged == true
          && contains(github.event.pull_request.labels.*.name, 'workflows')
        run: |
          echo "ERROR: The 'workflows' label is present."
          exit 1

      - name: Extract ref
        id: extract-ref
        run: echo "ref=${{ github.event.repository.default_branch }}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}
          fetch-depth: 0

      - name: Check version tag
        run: |
          if git tag --points-at HEAD | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
            exit 0
          fi
          echo "ERROR: There needs to be a version tag."
          exit 1

  update-package:
    name: Update package
    runs-on: ubuntu-latest
    needs:
      - run-checks
    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${{ github.event.repository.default_branch }}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}
          fetch-depth: 0

      - name: Prepare tags
        id: tags
        run: |
          echo "DIGEST=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
          echo "REF_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup buildkit
        run: |
          curl -fsSL https://github.com/moby/buildkit/releases/download/v0.16.0/buildkit-v0.16.0.linux-amd64.tar.gz \
            | sudo tar -xzf - -C /usr/local 

      - name: Start buildkit daemon
        run: |
          sudo --non-interactive --shell <<END_SUDO
            install -d -m 0750 -o root -g docker /run/buildkit
            buildkitd &
            while ! test -S /run/buildkit/buildkitd.sock; do sleep 1; done
            chgrp docker /run/buildkit/buildkitd.sock
          END_SUDO

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          buildctl build \
            --frontend dockerfile.v0 \
            --opt platform=linux/amd64 \
            --output type=image,name=${{ format('ghcr.io/{0}:{1}', github.repository, 'latest') }},push=true \
            --export-cache type=gha \
            --import-cache type=gha
